# Generated by Django 3.1.3 on 2020-12-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201202_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Username must be unique try with numbers too', max_length=100, null=True, unique=True),
        ),
    ]
