# Generated by Django 3.1.3 on 2020-12-04 16:07

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_pictures_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='images_count',
            field=models.IntegerField(null=True, verbose_name=models.ImageField(null=True, upload_to=images.models.upload_location)),
        ),
    ]
