# Generated by Django 3.1.3 on 2020-12-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_pictures_images_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='images_count',
        ),
    ]
